### ISSUE TITLE
Question: Read Zip file from offset

### ISSUE THREAD

**Issue by Turbo87** [zip-rs/zip#105]
I have a rather strange usecase. I'm trying to read `.cupx` files, which seem to be two Zip files concatenated. Is it possible to use `zip-rs` to:

- read the first Zip file?
- figure out the length of the first Zip file (= the offset of the second Zip file)?
- read the second Zip file using the above offset?

It seems that the `ZipArchive` struct already has a concept of an `offset`, I'm just not sure if that could be used for the above purposes. 🤔

**Comment by rylev** [comment]
I'm not sure his crate necessarily needs to handle this. In #58 we're discussing making some of the lower level aspects of the crate public. With this you would be able to read the header of the first file, and then break the file reader into two using something like [`Read::take`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.take). I'll keep this open for now, but I want to wait to see if #58 addresses this.

**Comment by Plecra** [comment]
The crate's extraction algorithm is designed in a way that precludes extracting this kind of stream. We need to know how long the file is in advance to find the central directory.

It'd be possible to implement an alternative extractor that used the local file headers, and this feature would fall out quite naturally. Though aiui, this doesn't give us all the context needed to fully parse the ZIP data, and would only work on particularly well-formed files.

That is to say, I'd be surprised if the library supported this any time soon - Like you said, it's a rather strange usecase 😉

**Comment by Plecra** [comment]
Looking at this again, I think you might be able to do this just fine with the current crate: You can create a custom `impl Read + Seek` which automatically applies the offset for all reads that `zip` makes. If anyone ever needs some more metadata able the zip file to do something similar, please open a new issue :) It'll be an easy addition
