### ISSUE TITLE
Support custom compression methods

### ISSUE THREAD

**Issue by dbregman** [zip-rs/zip#112]
I believe this should be quite simple to do, basically:
1) allow setting the uncompressed size on FileOptions
2) treat "Unsupported" compression methods as "Stored", and let the user write already compressed data.

**Comment by Plecra** [comment]
It seems like this would be easy to misuse, and create files that can't be read by ZIP implementations. What is the compression method you want to use? Since we eventually want to support any ZIP file, we'd welcome a PR for an extra compression method from the spec.
