### ISSUE TITLE
Move to a GitHub organization or add collaborators to this repository?

### ISSUE THREAD

**Issue by messense** [zip-rs/zip#123]
As the README says: 

> Unfortunately, due to a lack of time and loss of interest, this project will no longer be actively maintained.

Since `zip-rs` crate is widely used([crates.io reverse dependencies show 120](https://crates.io/crates/zip/reverse_dependencies)), how about moving this repository to a GitHub organization or add collaborators to this repository and let the community maintain this crate?

**Comment by AlexApps99** [comment]
@mvdnes Any news on this? As one of the many users of this crate, I would appreciate it being maintained.

As an alternative to the suggested solutions above, if you don't want to make an organisation or add collaborators maybe this crate's ownership could be transferred to someone else and a community run fork could be made?

Thanks :)

**Comment by mvdnes** [comment]
I have no idea who to add as a collaborator, and no-one has volunteered yet, so unfortunately no change in status.

**Comment by tinaun** [comment]
i can be a maintainer if you need one

**Comment by rylev** [comment]
@mvdnes I'm also happy to help. I work in Rust full time so I have the time and the need to maintain this project.

**Comment by mvdnes** [comment]
@tinaun, @rylev: Are you still interested?
I think the way to go is that I will add some of you as a collaborator, while keeping the crates.io publishing rights to myself.

**Comment by rylev** [comment]
Sounds good to me. Work has picked up a bit so I won’t have quite as much time as a few weeks ago, but I can start by addressing issues.

**Comment by rylev** [comment]
@mvdnes while I'm waiting for the invite, I'll start addressing some of the issues.

**Comment by rylev** [comment]
I am now maintaining this crate. Let me know if you have any questions! ❤

**Comment by mvdnes** [comment]
After an e-mail showing interest in being a reviewer, I have also sent an invitation to @Plecra for being a collaborator.

**Comment by Plecra** [comment]
@rylev Would you mind explaining how you manage PRs? I'm new to being an OS maintainer ^^

In particular, I was surprised by your response in #116 

> This seems somewhat brittle, but I think we merge this without addressing this for now

The PR seems like a good opportunity to address these kind of issues while the design in fresh in the author's mind - why wait to make the fix?

**Comment by rylev** [comment]
@Plecra welcome! OSS maintenance is a bit of an art. I've found maintainers that are extra pedantic tend to turn away contributions. The thing you linked to is not ideal, but it's also not wrong, and it's not the main thrust of the PR. I think we could last a while with it as is. I didn't feel that it merited blocking the entire PR just to address that side issue.

**Comment by rylev** [comment]
@Plecra I think we should establish a few ground rules for collaboration. My suggestions:
* No pushing to master
* Try our best to not merge our own PRs (we should come up with some way to handle things like vacations or breaks)
* Any breaking changes require both our consent.

Thoughts?

**Comment by Plecra** [comment]
Sounds good to me. On the topic of breaking changes, how strictly do you want to follow SemVer? I think RFC 1105 should be appropriate most of the time, and we can handle special cases as they come.

**Comment by rylev** [comment]
I'm not a super stickler for SemVer. I think we can try our best to reserve breaking changes for 0.x releases, and release more often than not. I think we can avoid causing too much headache by doing incremental design.

**Comment by rylev** [comment]
@Plecra I'd like to clarify ownership over the maintenance of this crate. While I'm very much happy contributing and helping with its upkeep, I'd like for you to be _the_ core maintainer who is ultimately responsible for if something gets merged or decides on policies. I appreciate you continuously asking for my input, and I'm happy to continue to give that input, but I believe you're more invested and more qualified to maintain this crate. Thoughts?

**Comment by Plecra** [comment]
I'm flattered! I expect it'll be good to make the ownership clear soon to avoid it becoming a problem, and I'd gladly take that on. You better not be expecting to be let off the hook though! Your thoughts have been very helpful 😛 

Would you mind sharing your position the ownership of the crate @mvdnes ? Asking you to handle releases atm is fine, but I'd like to know what the long-term plan is.

**Comment by mvdnes** [comment]
At first I wanted to see how you would handle the new maintainership, before transferring ownership completely.
I think you are doing a good job, so I am open to transfer this project at this moment. You may decide if you want an organisation or to a single user.

**Comment by Plecra** [comment]
Great to hear. I'd like to move it into the https://github.com/zip-rs organization, which I've also sent you an invite for in case you want to stay involved.

**Comment by Plecra** [comment]
And here we are!

**Comment by mvdnes** [comment]
I have also invited you to be an owner on crates.io for this project.
