### ISSUE TITLE
Support async.await compression/decompression with Tokio 0.2

### ISSUE THREAD

**Issue by gliderkite** [zip-rs/zip#124]
As the title suggests, it would be great to have support for asynchronous APIs that can be used with Tokio 0.2.

**Comment by zacps** [comment]
I am somewhat working on this currently, but I'm not especially familiar with implementing async/await so it may take a while (or be abandoned).

**Comment by Plecra** [comment]
We won't be trying to add this to 0.6 again, due to the size of the changes it would need, and the complexity it would add to the library. If anyone's thinking of trying to make a PR, please try to discuss it with us first 😊

**Comment by Plecra** [comment]
I'm afraid zip is staying inside the sync ecosystem for now.

**Comment by Plecra** [comment]
That's fantastic, thanks for linking it here! I'll put a pin in that one :) I'd like to be able to link to it in our readme
