### ISSUE TITLE
Upgrade to time v0.2

### ISSUE THREAD

**Issue by jhpratt** [zip-rs/zip#131]
I can do this if desired. Would a PR be accepted?

**Comment by rylev** [comment]
👋 Hi, @jhpratt. New maintainer here. I'm happy to take a PR for this. Let me know if you're still interested in doing this, otherwise I can do it.

**Comment by jhpratt** [comment]
I don't have a ton of time to work on something like this right now. I'd be more than happy to answer any questions you may have, though!

**Comment by Plecra** [comment]
Was there a reason you wanted to continue using the `time` crate? Is it somehow more appropriate than `std::time` for zip files?

**Comment by notmandatory** [comment]
I have a PR to update the `time` dependency to "0.3", see #254.  This needs to be upgraded ASAP due to current `time` version causing this crate (and it's dependents) to fail `cargo audit`.

**Comment by zamazan4ik** [comment]
Closed since the master is upgraded with https://github.com/zip-rs/zip/pull/254
