### ISSUE TITLE
Expose compressed size written to zip file/archive

### ISSUE THREAD

**Issue by juarezr** [zip-rs/zip#132]
This can allow one to split the files/contents in multiple archives.

``` rust
let mut zip = zip::ZipWriter::new(file);
let options = FileOptions::default().compression_method(zip::CompressionMethod::Stored).unix_permissions(0o755);
zip.start_file("test/filename.txt", options)?;
zip.write_all(b"Hello, World!\n")?;

let bytes = zip.get_compressed_bytes();
// expose information after writing ^^^
```

**Comment by rylev** [comment]
So I get the need to have the underlying bytes. I'm wondering if we should bikeshed the API a bit. `get_compressed_bytes` seems a little clunky of a method name. Would it make more sense to be able to convert a ZipWriter to a ZipArchive?

**Comment by juarezr** [comment]
I haven't seriously thought about the best API color, but in my rush to production [app](https://github.com/juarezr/solrcopy) I already wrapped ZipWriter to a [Archiver](https://github.com/juarezr/solrcopy/blob/master/src/save.rs#L18) and a [ArchiveReader](https://github.com/juarezr/solrcopy/blob/master/src/ingest.rs#L69). :smiley:

**Comment by Plecra** [comment]
This information is already available through the `Write` trait - is there a reason you need it directly through `zip`s API? Since I doubt it's relevant to most users, I'm not sure the global cost is worth it.

```rust
use std::io;

struct CountedWrite<W: io::Write> {
    inner: W,
    written: u64
}

impl<W: io::Write> CountedWrite<W> {
    fn new(inner: W) -> Self {
        Self {
            inner,
            written: 0
        }
    }
}

impl<W: io::Write> io::Write for CountedWrite<W> {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        let written = self.inner.write(bytes)?;
        self.written += written as u64;
        Ok(written)
    }
    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}
```
