### ISSUE TITLE
Review project licensing

### ISSUE THREAD

**Issue by Plecra** [zip-rs/zip#162]
...and ideally ensure that all of the current code is owned "by the project". I'm not particularly versed in this legal side of things, but the impression I get is that it will get more tedious to resolve the longer we leave it.

@rylev, @mvdnes, how do you think we should approach this? Maybe I'm overthinking it?

I'll keep track of what I find while reading up on it here...

**Comment by rylev** [comment]
Do we have examples of other projects that make this explicit?

**Comment by Plecra** [comment]
Turns out GitHub already makes this explicit: PRs *are* agreements to place the code under the project's own license, so I don't think there's any need for us to add one, and it'd just create friction for contributions.

https://help.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license

I would like to address the license we're using though - do we really want users to include a copy of it in their own work? It seems that it applies to any program depending on `zip`. Simply sharing a compiled binary would technically breach the MIT License as it is.

**Comment by Plecra** [comment]
After looking through [the popular open source licenses](https://opensource.org/licenses/alphabetical), I quite like the [Zlib License](https://opensource.org/licenses/Zlib), especially since its wording is so straightforward.

@mvdnes, as (I assume) the main owner of the crate's code, what would you think of dual licensing it as `MIT OR Zlib`? I like the idea of protecting users from some bad actor who managed to justify their own copyright over the crate

**Comment by JockeTF** [comment]
Perhaps it would make sense to dual-license under MIT and Apache 2 since it's what Rust project often seem to do?

**Comment by Plecra** [comment]
As I understand section 4.a of the Apache 2 license, the same restriction applies to users. I don't think it'd be unfair to choose to simply place that restriction on users of the crate, but I'd prefer it to be simpler.

**Comment by mvdnes** [comment]
I like the MIT license due to it's simplicity, and am not opposed to the Apache 2 license. If you have any good arguments in changing the current license, let me know.

**Comment by Plecra** [comment]
My reasons for avoiding the MIT license are fairly simple: It is easy for a hobbyist to include the `zip` crate in their project, and once they have, they might well create a program they'd like to share.

If they were to share that binary without the license (which I think is easy to do innocently), they'd be breaking the terms of the MIT license, and technically at risk of any of `zip`'s contributors suing them. I'd be very surprised if that were ever to *actually* happen, but when we're talking about the law, I'd rather not play with fire.

I have started using the Zlib license for its simplicity too. Imo it's actually simpler than the MIT license (It doesn't use awkward language like "furnished" :/), but there could well be an even better license around.

**Comment by Plecra** [comment]
What we've got is fine. Dual licensing would be cool but gets iffy w.r.t previous contributions
