### ISSUE TITLE
miniz_oxide 0.4.0 breaks 1.34.0 MSRV

### ISSUE THREAD

**Issue by Plecra** [zip-rs/zip#170]
Upstream issue: https://github.com/Frommi/miniz_oxide/issues/85

**Comment by rylev** [comment]
Given that our "hard" MSRV policy is 4 versions before the current stable, I would not be against bumping the MSRV.

**Comment by rylev** [comment]
@Plecra thoughts on the 1.34.0 MSRV. Is it worth keeping in this case?

**Comment by Plecra** [comment]
I don't think there's an urgent need to decide. I'm happy to wait and see how miniz_ozide handles it.

We can address it when we're ready to make a release.

**Comment by rylev** [comment]
@Plecra I'd rather not leave the build broken, so as long as we can fix the build, I agree.

**Comment by mbrubeck** [comment]
This was fixed in https://github.com/Frommi/miniz_oxide/pull/95.

**Comment by zamazan4ik** [comment]
Closed since we bumped our MSRV to 1.54.0
