### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by rylev** [zip-rs/zip#173]
The docs are currently fairly sparse. We should make sure to improve them before the next release.
![Capture](https://user-images.githubusercontent.com/1327285/86375044-8407d700-bc85-11ea-970a-4c8c9ee35947.PNG)

**Comment by zamazan4ik** [comment]
We need to add documentation notes about our current state of AES state in the library. Current implementation at least has no review from cryptography specialists and can have some security holes. https://github.com/zip-rs/zip/pull/203

**Comment by Plecra** [comment]
We should still improve our docs, but this issue's not specific enough :)
