### ISSUE TITLE
Implement path sanitization

### ISSUE THREAD

**Issue by Plecra** [zip-rs/zip#181]
This was a surprise...

https://github.com/mvdnes/zip-rs/blob/62dc40678e2d90cccc1e583916b8cba47a6f3cb5/src/write.rs#L605-L616

This ignores all `Component::ParentDir`s, which could create very odd behavior in CLIs:

```SH
> cat bar
abc
> zip ./foo/../bar -o out
> unzip out into
> cat into/foo/bar # `bar` just moved into the `foo` directory! Wha?
abc
```

## Solution

Imo, this is quite clearly a logic bug, and should simply be remedied by including `ParentDir`s. However, this is the behavior documented for [`ZipWriter::start_file_from_path`](https://docs.rs/zip/0.5.6/zip/write/struct.ZipWriter.html#method.start_file_from_path), so we might not want to do that...

I'm tempted to simply deprecate the method, and warn users about the strange behavior. The implementation also uses `to_string_lossy`, which I don't think is really appropriate.

**Comment by Plecra** [comment]
API that needs to be updated:

https://github.com/mvdnes/zip-rs/blob/0b46263eac1541d885dcee65582e2726056acd1a/tests/extract.rs#L8-L11
https://github.com/mvdnes/zip-rs/blob/0b46263eac1541d885dcee65582e2726056acd1a/src/read.rs#L325-L328
https://github.com/mvdnes/zip-rs/blob/0b46263eac1541d885dcee65582e2726056acd1a/src/read.rs#L612-L619

**Comment by jamesmcm** [comment]
Deprecating this breaks CI pipelines that deny warnings. 

For now I worked around it by adding `#[allow(deprecated)]` but in general I think it'd be best to only deprecate when the deprecation message can have clear instructions of what is best to use instead. Since the vast majority of zip files won't be affected by this issue (despite it being an important issue).

**Comment by Plecra** [comment]
Though it seems strange, I wouldn't mind adding a `mangled_name` method to direct people to. Would that do the trick @jamesmcm ?

**Comment by jamesmcm** [comment]
Yeah, I think it's a good solution for now. Mainly since most zip files won't be affected.
