### ISSUE TITLE
Decide on crate priorities

### ISSUE THREAD

**Issue by Plecra** [zip-rs/zip#184]
For the sake of simplicity, I'd like to agree on what the crate prioritizes in its APIs. We can refer to this decision when responding to PRs and writing implementations without needing a discussion.

I see 4 relevant properties of our API:

- Permissiveness
    - Sadly the ZIP format is misused quite a lot, making this important for many users.
    - Should we require at least one real-world example before expanding the valid inputs?
- Correctness
    - Mirrors how permissive the parser is.
    - We should at least ensure the parser won't disagree with the spec on any input
    - Do users need to know why parsing failed? Simply returning `io::ErrorKind::InvalidData` might be quite handy
- Speed
    - We should create some benchmarks if this is important
- Ergonomics
    - We want people to be able to implement formats like [`epub`](https://docs.rs/epub/1.2.2/epub/) on top of our parser, as well as ad-hoc ZIP reading and GUIs.
        - This may mean providing multiple APIs, or tidy use of generics
    - The API should hide as many of the eccentricities of the format as possible

> Edit: We could also consider size efficiency. It's possible for a ZIP file to contain niches between its files that we could use if we know the size of the data we're adding. The same idea could be used to allow in-place file editing for smaller files

I'd like to favor permissiveness and ergonomics, while keeping the speed of the parser in mind and avoiding decisions that create a lot of extra work for it.

### Tasks

- [ ] Add our decision to the crate-level documentation

**Comment by rylev** [comment]
My own personal order or priorities is:
* Ergonomics 
* Correctness 
* Speed 
* Permissiveness

I do understand permissiveness to be important, so I'm not advocating that we don't consider it, but it is the least important for my own use cases. That being said, I'd love to design an API that allowed users to handle uncommonly formed zip files even if the API for doing so was not super ergonomic (i.e., required more boiler plate) as long as the "happy-path" remained ergonomic.

**Comment by Plecra** [comment]
And how permissive do we want to be with the Zip files we're reading? There are quite a few ways the metadata can be invalid, like local headers disagreeing with the central directory. It could make sense to emit errors when we encounter something like that, but most users will want the library to do its best to recover (we've got a bunch of issues asking for this very thing)

**Comment by rylev** [comment]
This is a really great question. I imagine a large majority of our users will be reading zip files and will want it to just work™ though for some extreme use cases it might make sense to simply expose parsing primitives to the user who can compose those primitives however they like. I'm personally not interested in creating a library that can read any zip file you throw at it, but again that's just my personal interest. As long as well formed zip files are trivial to read, I'm ok with users having to work a tiny bit harder to read malformed files.

**Comment by Plecra** [comment]
I imagine we're going to find it tricky to expose these decisions in the middle of parsing. We'll have to decide how to handle contradictory/misleading data when we can't ask the user.

Do you agree that we should try to give the user *something* instead of an error when that happens? And, ideally, a signal that it did.

**Comment by BenjaminRi** [comment]
What about introducing a *strict* mode that only parses zip files that are spec-compliant to the last bit? This option would be active by default, but you could choose a mode that is less strict and allows such non-compliant zip files. You could specify this flag initially when you open the file, and you would have to opt into the spec-breaking behaviour, which is in line with Rust's design principles of having to opt into unsafe things. Application programmers then have the choice. As a bonus point, activating the *strict* mode gives you the exact cause of the spec violation as an error and programmers could then display a warning in e.g. a GUI and fall back to the non-strict mode to open the zip file anyway.

**Comment by Plecra** [comment]
https://github.com/mvdnes/zip-rs/blob/5afd11760403c31da8c14b3e65bddf7af69cbc90/src/lib.rs#L14-L31

@rylev How's this summary?

**Comment by rylev** [comment]
> Archives won't be interpreted in any way that deviates from the spec. 

I think I understand what you mean by this, but it might be interpreted the wrong way: "We will only read spec compliant archives.". I believe the second sentence is meant to qualify this by saying if the archive isn't spec compliant but there are no ambiguities, we will still parse the archive. Perhaps we can clarify this point?

"While we aim to accept archives that are not 100% spec compliant (as many exist out in the wild), if there is any ambiguity, we will force the user to resolve this before continuing" - Something like this?

**Comment by Plecra** [comment]
How about "Archives will be accurately represented by the API. If the meaning of any metadata is unclear, the user will need to resolve it."?

**Comment by rylev** [comment]
Sounds really great!

**Comment by Plecra** [comment]
All that's left to do here is move the description from 0.7 to master. I'm in no hurry to do that until we've brought the actual API in line with it.

**Comment by Plecra** [comment]
Lol. It was a good attempt ❤️
