### ISSUE TITLE
Enable new Travis repo

### ISSUE THREAD

**Issue by palfrey** [zip-rs/zip#199]
The build badge points to the old name, and https://travis-ci.org/github/zip-rs/zip hasn't been activated yet.

**Comment by rylev** [comment]
This might be a good time to discuss if we're happy with Travis and Appveyor. I'm not against staying with them, but something like GitHub Actions could cut the number of CI configs we have in half.

**Comment by palfrey** [comment]
Ah. I see #140 removed the appveyor config, but the build badge is still there. Fine with whichever option, but should probably clean out the remnants of the other choices!

**Comment by Plecra** [comment]
Sorted in b9f2d9419a9c6248178e09687704b7671628017a
