### ISSUE TITLE
API for reading raw file content

### ISSUE THREAD

**Issue by nicklaswj** [zip-rs/zip#205]
Hi all.
I'm using zip-rs to only read zip archives (i.e. not decompress the content), and thus have default-features = false.
However the two variants of the enum CompressionMethod, Deflated and Bzip2 only exist if respectively the two features "flate" and "bzip2" are turned on. Currently this is not a big problem if you want to know the compression method, since you can just match on the Unsupported(v) variant and check the value v, however I can see that you are deprecating this variant.

So what am I suppose to do if I want to know the compression method but not turn on the decompression/compression features? Second is there a good reason for the variants Deflated and Bzip2 to be behind a feature flag?

Otherwise thanks for a really useful and easy to use crate :)

Nicklas

**Comment by Plecra** [comment]
Ah, another consequence of my clumsy use of `deprecated`. The intention is that `CompressionMethod` will contain every valid variant, at which point `Deflated` and `Bzip2` will be usable without the feature like you mentioned.

There are a few issues like this (#198) that shouldn't take much work to resolve, so I'm making 5.8 a priority.

**Comment by Plecra** [comment]
I'm looping https://github.com/zip-rs/zip/pull/209#issuecomment-725941117 back into this issue, since the changes seem closely linked.

Would you be able to explain what you are reading the raw content of the files for? It'd be good to know what the API needs to give access to.

**Comment by Plecra** [comment]
This is implemented as the [`ZipArchive::by_index_raw`](https://docs.rs/zip/0.5.12/zip/read/struct.ZipArchive.html#method.by_index_raw) API
