### ISSUE TITLE
Allow custom DEFLATE compression level

### ISSUE THREAD

**Issue by MCOfficer** [zip-rs/zip#212]
I'm compressing a massive text file using this crate, which takes a lot of time using `FileOptions::default()`. I experimented with 7z, and setting the compression level to 1 produces almost the same filesize, but is significantly faster.

However, It seems like the compression level can't be set using this crate. Is this correct?

**Comment by Plecra** [comment]
That's right, we don't support compression configuration just yet. Our backwards compatibility guarantees prevent us from adding it to the current API, so it'll need to be properly added in the next release.

That said, this would at least be *possible* with [the raw reading API](https://github.com/zip-rs/zip/issues/205#issuecomment-727584125) we're adding. Would that be any help for you?

**Comment by MCOfficer** [comment]
> 
> 
> That's right, we don't support compression configuration just yet. Our backwards compatibility guarantees prevent us from adding it to the current API, so it'll need to be properly added in the next release.
> 
> That said, this would at least be _possible_ with [the raw reading API](https://github.com/zip-rs/zip/issues/205#issuecomment-727584125) we're adding. Would that be any help for you?


It may be, but i feel like i'm not getting it. How would this help me with creating a zip file?

**Comment by Plecra** [comment]
It doesn't 😅 I misunderstood what you were doing. Annoyingly, there's quite a lot of bookkeeping involved that I can't simply factor out. I don't expect this to be solved before the new year.

**Comment by 0ax1** [comment]
+1 on that this would be a great addition. Are there any updates on the status?

**Comment by marcospb19** [comment]
+1, we would need this to solve https://github.com/ouch-org/ouch/issues/52.

@Plecra could you give a status update on this? How hard is it to implement? I'd probably be able to help by the end of this year depending on the difficulties involved.

**Comment by marcospb19** [comment]
Does #286 closes this? @Plecra?

**Comment by Plecra** [comment]
It sure does! These days, `writer.start_file("oopsies", FileOptions::default().compression_level(n)))` will let you write a file with the compression level you like. Thanks for the bump ^^
