### ISSUE TITLE
how do I open a zip file with a password?

### ISSUE THREAD

**Issue by t-heu** [zip-rs/zip#214]
I didn't understand how to use this lib, how do I open a zip file with a password? any code demonstrations?

**Comment by BenjaminRi** [comment]
@t-heu There are some unit tests that show how to open a zip file with password. You can find them here: https://github.com/zip-rs/zip/blob/master/tests/zip_crypto.rs

In particular:

```rust
// Correct password, read contents
let mut file = archive
	.by_index_decrypt(0, "test".as_bytes())
	.unwrap()
	.unwrap();
let file_name = file.enclosed_name().unwrap();
assert_eq!(file_name, std::path::PathBuf::from("test.txt"));

let mut data = Vec::new();
file.read_to_end(&mut data).unwrap();
assert_eq!(data, "abcdefghijklmnopqrstuvwxyz123456789".as_bytes());
```

where `archive` was opened just like you would open an unencrypted zip file. In this example, `test` is the password.

What I'm puzzled about is that the functions `by_index_decrypt` and `by_name_decrypt` somehow don't show up in the documentation... See: http://mvdnes.github.io/rust-docs/zip-rs/zip/read/struct.ZipArchive.html

@Plecra is it possible that the documentation, as linked on https://crates.io/crates/zip , is out of date?

**Comment by t-heu** [comment]
where do I pass the zip file?

Error: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Invalid zip header")`
```
let reader = std::io::Cursor::new("zip/ok.zip");
  let mut archive = zip::ZipArchive::new(reader).unwrap();

  let file = archive
  .by_index_decrypt(0, "1234".as_bytes())
  .unwrap()
  .unwrap();
  let file_name = file.enclosed_name().unwrap();
  println!("{:?}", file_name);
```

**Comment by BenjaminRi** [comment]
The second example looks good to me. You open the archive correctly. The `InvalidArchive("Invalid zip header")` error is unusual. Do you know the exact method with which the archive was encrypted? This library only supports ZipCrypto. It does not support AES256 and in particular, it does not support any encrypted headers.

**Comment by t-heu** [comment]
so that's it, can you tell me any suggestions for working with AES-256?

**Comment by BenjaminRi** [comment]
There is a pending pull request that looks promising: https://github.com/zip-rs/zip/pull/203
You are invited to try out this fork and, if you so choose, to give feedback and contribute bug fixes and improvements, such that a future release can contain AES256 decryption.

**Comment by t-heu** [comment]
I'll take a look, thanks.

**Comment by Plecra** [comment]
Thanks for always being so helpful @BenjaminRi ! That's exactly how to use the decryption API at the moment.

I'll keep in mind the need for AES decryption 😃
