### ISSUE TITLE
Broken files after compression

### ISSUE THREAD

**Issue by 1271** [zip-rs/zip#216]
Hi. 
When using compression (`CompressionMethod::Bzip2` / `CompressionMethod::Deflated`), some files in the archive are broken. (examples of files in the attachment)

If you use `CompressionMethod::Stored`, files are saved correctly

[example.zip](https://github.com/zip-rs/zip/files/5782795/example.zip)
[broken_archive.zip](https://github.com/zip-rs/zip/files/5782816/broken_archive.zip)

```rust
use std::fs::File;
use zip::CompressionMethod;
use zip::write::FileOptions;
use zip::write::ZipWriter;

let files = vec!["file1", "file2"...];
let arc_opt = FileOptions::default().compression_method(CompressionMethod::Deflated);

let cursor = Cursor::new(Vec::new());
let mut archive = ZipWriter::new(cursor);

files.iter().for_each(|file| {
    archive.start_file(&file, arc_opt.clone()).unwrap();

    let mut file_buf = vec![];

    File::open(file).unwrap().read_to_end(&mut file_buf).unwrap();

    archive.write(&file_buf).unwrap();
}

let data = archive.finish().unwrap();

File::create(&archive_path).unwrap().write_all(data.into_inner().as_ref()).unwrap();
```

Features flags do not affect the result:
```toml
zip = "0.5"
```

```toml
zip = { version = "0.5", features = [ "deflate-zlib", "deflate-miniz" ] }
```

Am I missing something?
Thanks for the any help.

**Comment by Tamschi** [comment]
How large are the files in question? This library has a few silent overflow issues when ZIP limits are exceeded.

**Comment by zamazan4ik** [comment]
@1271 Thanks for the issue! Sorry for so looooong response time - I am even not sure if it still affects you or you have just chosen another library. Now I am trying to reproduce it locally on the `master` branch. If you have any additional information - please share it here.

**Comment by 1271** [comment]
hi @zamazan4ik
Thanks for replay.

Yeah, it's broken now.

Original file size (216822 bytes):
![изображение](https://user-images.githubusercontent.com/1452243/150693237-d67c791c-55c7-415a-8a59-67f1b376e5a0.png)

After `zip-rs` (63747 bytes):
![изображение](https://user-images.githubusercontent.com/1452243/150693261-618c86c7-32e2-4476-9206-04933d0d7f8f.png)


At the same time, small files (checked for 2kb) everything works as it should.

Tested on windows and linux

rust version: 1.58.1 


`zip-rs` explicitly "cuts off" some of the content. Image after comression.


Hex data:
Original (middle of file):
![изображение](https://user-images.githubusercontent.com/1452243/150693657-70c725cc-3289-4ff3-8b55-3d569ea61d89.png)


After `zip-rs`:
![изображение](https://user-images.githubusercontent.com/1452243/150693570-dcb1fcc3-f6a7-4607-9cf2-041bc8a62d0b.png)

**Comment by zamazan4ik** [comment]
Can you prepare please a repo with "just to run" example? I am trying to reproduce it locally with a master branch but unfortunately without success

**Comment by zamazan4ik** [comment]
Even on `0.5` I cannot reproduce it. My guess is that it is possibly something Windows-related and I need to investigate it on a Windows machine.

@1271 if you have a chance, can you check the same sample for you on something Linux-based? I guess WSL can be a good start point.

**Comment by 1271** [comment]
@zamazan4ik 
My main system is linux. Although windows is currently enabled.
But it works the same way (broken on linux too)

Check it

https://github.com/1271/zip-rs-test

**Comment by zamazan4ik** [comment]
@1271 as far as I see the problem is in this line in your example: https://github.com/1271/zip-rs-test/blob/master/src/main.rs#L32

If you replace `write` with `write_all`, all works as expected. I need to dig a little bit deeper, why it works in this way and is it our issue or not.

@Plecra do you have any ideas?

**Comment by 1271** [comment]
Oh i see.
The funny thing is that it works great with text.
Thanks, this solves the problem. 

Anyway, if the problem is not on your side, I think the issue can be closed.

Thanks for help

**Comment by Plecra** [comment]
Yes, this is a slightly confusing behaviour of the `std` API - `Write::write` actually only does partial writes! This is super useful for library code, but just annoying when you don't know about it. I'm glad the solution worked out :)

**Comment by zamazan4ik** [comment]
@Plecra Since our users have problems with this API, maybe will be a better idea to document such behavior? Or even remove it from public use (but you say that it's useful for the library code)?

**Comment by Plecra** [comment]
<https://doc.rust-lang.org/stable/std/io/trait.Write.html#tymethod.write>
> This function will attempt to write the entire contents of buf, but the entire write might not succeed, or the write may also generate an error. A call to write represents at most one attempt to write to any wrapped object.

This behaviour is already documented by `std` - new Rust users can stumble on it but typically find help in the community channels. `zip` behaves as people who know about the `Write` trait expect.

Adding a line to the documentation would be fine 🤷 My guess is that this isn't a common problem at all - it's unfortunate that in this case they weren't able to be pointed in the right direction.

**Comment by 1271** [comment]
@zamazan4ik @Plecra 
My main language is not rust, but I sometimes use it to write handy stuff.
Thanks for your help, the problem is completely solved.
I was initially confused by the fact that only a part of the files broke.
I don't think you need to change anything in your code. Everything works great. Thanks for your hard work! :+1:
