### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by BenjaminRi** [zip-rs/zip#218]
In issue #214, I noticed that the documentation is out of date.

Go to https://crates.io/crates/zip and click "Documentation" or directly go to http://mvdnes.github.io/rust-docs/zip-rs/zip/index.html and it is apparent that the documentation is old.

Important API calls like `by_index_decrypt` are missing.

**Comment by AutomatedTester** [comment]
Just came across the examples directories too which seem to be out of date too. E.g the `extract.rs` file uses `enclosed_name()` but I can't seem to find that. I am guessing the new API is `name_raw` or just `name`

**Comment by Plecra** [comment]
Oh yikes, I'd been assuming we were linking to https://docs.rs . I don't have control over those GH pages. On it!

**Comment by Plecra** [comment]
That should fix it! Just waiting on docs.rs' build queue 😃
