### ISSUE TITLE
Wrong minimum version of (likely) thiserror

### ISSUE THREAD

**Issue by Tamschi** [zip-rs/zip#219]
If you run

```sh
cargo +nightly update -Z minimal-versions && cargo +nightly check
```

on this project (and require at least `crc32fast@1.1.1`, since that crate has [a similar bug](https://github.com/srijs/rust-crc32fast/issues/18)), you should see the build fail with multiple errors like this one:

```sh
error[E0277]: `?` couldn't convert the error to `ZipError`
   --> […]\.cargo\registry\src\github.com-1ecc6299db9ec823\zip-0.5.9\src\write.rs:713:35
    |
668 | fn write_central_directory_header<T: Write>(writer: &mut T, file: &ZipFileData) -> ZipResult<()> {
    |                                                                                    ------------- expected `ZipError` because of this
...
713 |     writer.write_all(&extra_field)?;
    |                                   ^ the trait `From<std::io::Error>` is not implemented for `ZipError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = note: required by `from`

error: aborting due to 137 previous errors
```

- - -

It seems that `thiserror` introduced a new feature between versions 1.0.6 and 1.0.7 without increasing their minor version.

I suggest specifying

```toml
thiserror = "1.0.7"
```

and, ideally, yanking all affected versions.

**Comment by Tamschi** [comment]
Sorry, I have to remove the version suggestion. The issue in `enumflags2_derive` currently makes it hard to figure out exactly which version is needed.

**Comment by Tamschi** [comment]
Found it, it's a bit later. I'll file this with `enumflags2` too, even though the upgrade here is enough to fix my build.

**Comment by Plecra** [comment]
Thanks for the bug report! I'd like to see this fixed, but I don't consider it a high priority. For now, it is blocked on updating to bzip2 0.4, which contains https://github.com/alexcrichton/bzip2-rs/pull/50

**Comment by zamazan4ik** [comment]
@Tamschi is the issue still appear with the latest `zip-rs`?

**Comment by Tamschi** [comment]
> @Tamschi is the issue still appear with the latest `zip-rs`?

Yes (and the faulty `crc32fast` versions aren't yanked, so increase the required version of that crate to `1.1.1` first, still). You may have to check with

```sh
cargo +nightly update -Z minimal-versions && cargo +nightly check --no-default-features
```

since otherwise some optional dependencies pull in really old versions of the `gcc` crate that aren't compatible with current `std` anymore.

**Comment by Tamschi** [comment]
Updating these two dependencies:

```toml
crc32fast = "1.1.1"
thiserror = "1.0.7"
```

makes `zip-rs` compile successfully with `-Z minimal-versions`.

**Comment by zamazan4ik** [comment]
Got it. I will update them in a couple of minutes. Thanks!

**Comment by zamazan4ik** [comment]
https://github.com/zip-rs/zip/pull/260

**Comment by zamazan4ik** [comment]
@Tamschi https://github.com/zip-rs/zip/pull/260 is merged. Can I close the issue?

**Comment by Tamschi** [comment]
It looks like my CI config on that project isn't in order so it isn't checking this online, but yes I made sure it works locally. Thank you!

**Comment by Tamschi** [comment]
(I just set up update notifications for this crate, so I'll see when the new version is published on Crates.)

**Comment by fujiapple852** [comment]
@zamazan4ik as of the latest master this crate does not compile with `minimal-versions` for the default features.  I've raised https://github.com/zip-rs/zip/pull/278 to address this.
