### ISSUE TITLE
by_name cannot find filenames with a leading root `/`

### ISSUE THREAD

**Issue by Stigjb** [zip-rs/zip#226]
I'm processing some files following the [Open Packaging Conventions](https://en.wikipedia.org/wiki/Open_Packaging_Conventions), where the archive contains `.rels` files that refer to the relevant target filenames in the archive. Sometimes these targets will have a leading root, for instance `/word/document2.xml`. `by_name` will return an err if I don't trim the leading slash manually.

**Comment by Plecra** [comment]
```rust
use std::io::{Read, Write};

fn main() -> zip::result::ZipResult<()> {
    let mut zip = zip::write::ZipWriter::new(std::fs::File::create("tmp")?);
    let options = zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Stored);
    zip.start_file("/word/document2.xml", options)?;
    zip.write(b"<Data/>")?;
    zip.finish()?;
    let mut archive = zip::read::ZipArchive::new(std::fs::File::open("tmp")?)?;
    let mut contents = Vec::new();
    archive.by_name("/word/document2.xml")?.read_to_end(&mut contents)?;
    assert_eq!(&contents, b"<Data/>");
    Ok(())
}
```

As far as I can tell, this works fine. Could you create a reproducible example?

**Comment by Plecra** [comment]
Feel free to reopen this if the issue is not resolved :)
