### ISSUE TITLE
InvalidPassword when decrypting ZipCrypto Deflate zip file (even though the password is right)

### ISSUE THREAD

**Issue by xa888s** [zip-rs/zip#233]
When trying to decrypt [this](https://crackmes.one/static/crackme/606b1faf33c5d418e8c4009e.zip) file with this library I get an incorrect password error, but using the `unzip` utility with the same password works. Password: `crackmes.one`.
Code:
```rust
fn main() {
    let file = std::fs::File::open("./606b1faf33c5d418e8c4009e.zip").unwrap();
    let mut zip = ZipArchive::new(file).unwrap();

    zip.by_index_decrypt(0, b"crackmes.one").unwrap().unwrap();
}
```
Output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPassword', src/main.rs:7:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by xa888s** [comment]
Just got it to work by adding `0x2C` to the end of the password, but I don't understand why?

**Comment by BenjaminRi** [comment]
@xa888s Hmm, interesting. I can reproduce it with the file provided. But 7zip has no issues with the file. We have to look into it. I actually looked over the 7zip implementation back when I wrote the Rust ZipCrypto implementation, and the logic seemed identical. Maybe we miss some offsets or padding or violate the spec in other ways.

**Comment by BenjaminRi** [comment]
In the function `ZipCryptoReader<R>::validate`, the password is considered invalid by the following logic:

```rust
        // PKZIP before 2.0 used 2 byte CRC check.
        // PKZIP 2.0+ used 1 byte CRC check. It's more secure.
        // We also use 1 byte CRC.

        if (crc32_plaintext >> 24) as u8 != header_buf[11] {
            return Ok(None); // Wrong password
        }
```

If we just comment out this check, it works and the file is extracted correctly. So it seems like a password CRC check failure, rather than a problem with the decryption itself.

So, either there is a bug in this check or the file doesn't comply with PKZIP.

**Comment by xa888s** [comment]
@BenjaminRi Thanks for checking this out, I'll probably just use a fork with that commented out for the time being, is there any unforeseen consequence in doing that?

**Comment by BenjaminRi** [comment]
@xa888s If you comment this out and the password is wrong, you "successfully" extract random garbage or it fails somewhere in the extraction stage. If you're certain that the password is correct, there's probably little harm in doing it - other than it being an ugly workaround ;)

**Comment by BenjaminRi** [comment]
Found the culprit. We are dealing with the Info-ZIP modification to the ZipCrypto format. So the file indeed does not comply with PKZIP as theorized above.

If we modify the function `central_header_to_zip_file` with the following printout `println!("Time: {:#04x}", last_mod_time);`, we see that the time field is `0x742a`.

We also see in our current password check that we expect `0xFB` but we get `0x74` in the last header byte. This `0x74` is the high order byte of the time field.

This behavior is documented in the 7zip code: https://github.com/kornelski/7z/blob/a6e2c7e401a3e5976e8522de518a169b0d8a7fac/CPP/7zip/Archive/Zip/ZipHandler.cpp#L1182

```cpp
          /* Info-ZIP modification to ZipCrypto format:
               if bit 3 of the general purpose bit flag is set,
               it uses high byte of 16-bit File Time.
             Info-ZIP code probably writes 2 bytes of File Time.
             We check only 1 byte. */

          // UInt32 v1 = GetUi16(_zipCryptoDecoderSpec->_header + NCrypto::NZip::kHeaderSize - 2);
          // UInt32 v2 = (item.HasDescriptor() ? (item.Time & 0xFFFF) : (item.Crc >> 16));

          Byte v1 = _zipCryptoDecoderSpec->_header[NCrypto::NZip::kHeaderSize - 1];
          Byte v2 = (Byte)(item.HasDescriptor() ? (item.Time >> 8) : (item.Crc >> 24));

          if (v1 != v2)
          {
            res = NExtract::NOperationResult::kWrongPassword;
            return S_OK;
          }
```

We currently don't have support for the Info-ZIP encryption, however, it looks like it could be added with little effort.
