### ISSUE TITLE
More ergonomic coupling between ZipFile and ZipArchive

### ISSUE THREAD

**Issue by smwoj** [zip-rs/zip#242]
I'm looking for a way to implement a function that given a ZIP archive and the name of a contained file returns an instance of `std::io::Read`. I think right now it requires self-referential structs or unsafe code ([as disussed in this SO answer](https://stackoverflow.com/a/67828823)), both of which I'd rather avoid.

Do you envision a good solution for my use case? If it doesn't require very complex changes in this crate I'd be happy to help with the implementation.

This is not a duplicate of https://github.com/zip-rs/zip/issues/147 as the iterator API mentioned in that PR would be one solution, but my use case could be solved in other ways (e.g.  if ZipArchive supported a consuming API to obtain a ZipFile-like value, which returned the ZipArchive once you're done with the particular file).

Thanks in advance!

**Comment by Plecra** [comment]
Adding a consuming API to the current iteration of `ZipArchive` is tricky, as we already have a number of variants of `by_name`. We'd probably want to provide `into_file`, `into_raw_file` and `into_decrypted_file`, all of which would need quite a lot of internal changes to support the change. I think if we were to support this, we'd need to use a self-referential struct for our own sanity 😁 
I think an implementation of this on top of https://docs.rs/gsrs would be handy. If someone wants to move a crate providing that API into the zip-rs organization, I'd be more than happy to help out.

As for complex changes that'd make this actually nice to use, the new API should let you write this along these lines

```rust
fn get_file(archive: Archive<fs::File>, name: &str) -> io::Result<Reader<fs::File>> {
    let file = archive
        .iter_mut()
        .find(|file| file.name() == name)
        .ok_or_else(|| io::Error::from(io::ErrorKind::NotFound))?;
    let file_clone = file.data.try_clone()?;
    // this is the magic - I'm making zip::Files (and the new Reader) actual generic types, so we can take ownership
    file.with_data(file_clone)
        .reader() // this is close to Result<io::Result<Reader<fs::File>>, LockedFile<fs::File>>
        .map_err(|_| io::Error::from(io::ErrorKind::PermissionDenied))?
}
```

Unfortunately this isn't so easy to make generic - we could alternatively write this function in terms of a `T: io::Seek + Clone`, but we wouldn't support `std::fs::File`s as they can't be cloned. (We could also implement it with `T: Default` using `std::mem::take`, but `fs::File` lets us down there too 😄). This is a persistent problem across the API: `io::Read` can't fully abstract away the differences between types like `&[u8]` and `fs::File`. My focus is on providing hooks in 0.7 that can be used to fiddle more with the guts of the crate

**Comment by Plecra** [comment]
On second thought, I think a new API like `fn Archive::split_inner(self) -> (Archive<()>, T)` should make this doable.

```
fn get_file<T>(archive: Archive<T>, name: &str) -> io::Result<Reader<T>> {
    let (archive, data) = archive.split_inner();
    let file = archive
        .iter_mut()
        .find(|file| file.name() == name)
        .ok_or_else(|| io::Error::from(io::ErrorKind::NotFound))?;
    file.with_data(data)
        .reader() 
        .map_err(|_| io::Error::from(io::ErrorKind::PermissionDenied))?
}```

The data needed for building a `zip::File` is currently kept deserialized, so I can't immediately see any reason this wouldn't work. I'll have to try it ^^

**Comment by Plecra** [comment]
Sorry for the unhelpful answer there! I'm afraid the status quo is that you should use a self referential struct to achieve the behaviour you want. I'm still looking at using the above solutions eventually.
