### ISSUE TITLE
Provide a streaming interface

### ISSUE THREAD

**Issue by doums** [zip-rs/zip#247]
Hi,

I'm not sure, but it doesn't seem possible to be able to stream the archive creation "end to end" with this crates. By end-to-end stream I mean adding the files by stream into the archive and at the same time streaming the produced zip file directly out while the zip file is being written. In this way, this will create an archive without having to write the entire archive file to memory or disk.

For example, one could create an archive and stream it to AWS S3 (upload or multipart upload) directly.

In JavaScript there is this library that provides a streaming interface -> https://www.npmjs.com/package/archiver

So I would like to know if I missed something on my side to implement this or if it's actually not possible with this crate ?

**Comment by Plecra** [comment]
`io::Read` is analagous to javascript's `ReadStream`, so you can simply create a `ZipWriter` with a `net::TcpStream` and the data will be streamed as you write to it
