### ISSUE TITLE
Permissions are not copied in raw_copy_file_rename

### ISSUE THREAD

**Issue by dzamlo** [zip-rs/zip#252]
When using the ` raw_copy_file_rename` method (and the ` raw_copy_file` method that call it), the permission are not copied.

The issue is with this line:
https://github.com/zip-rs/zip/blob/7edf2489d5cff8b80f02ee6fc5febf3efd0a9442/src/write.rs#L610

When calling the setters on `FileOptions`, the original one is not modified  because the `struct` is `Copy` and thus the method is called with an implicit copy and not a reference to the original one.

**Comment by zamazan4ik** [comment]
@dzamlo Thanks for the issue? Maybe you already have the proper fix for the library? Any PR is welcome!

**Comment by zamazan4ik** [comment]
Fixed in https://github.com/zip-rs/zip/pull/264
