### ISSUE TITLE
Possibly SIMD optimization in zipcrypto.rs

### ISSUE THREAD

**Issue by deeprobin** [zip-rs/zip#255]
https://github.com/zip-rs/zip/blob/master/src/zipcrypto.rs#L50
Wouldn't it make sense to work with [`__mm256_xor_ps`](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions/intrinsics-for-bitwise-operations-1/mm256-xor-ps.html) ([`core_arch::x86_64::__mm256_xor_ps`](https://rust-lang.github.io/stdarch/x86_64/core_arch/x86_64/fn._mm256_xor_ps.html)) in that case?

**Comment by BenjaminRi** [comment]
I agree with you that ZipCrypto unzip should be optimized (it is somewhat slow). I have to admit, I didn't think much about it, I simply wrote the naive implementation given by the documentation/paper. That is also how 7zip does it.

However, I don't quite understand your proposed optimization. You propose to vectorize the XOR of 32 bytes of values. Where can we apply that? The problem is that with every byte of input, the keys are shuffled with each other, and each byte of input depends on the previous byte. I don't see a simple way to vectorize this operation. Would you mind elaborating further?

**Comment by deeprobin** [comment]
@BenjaminRi 
Thank you for the information. If that's the case, then I don't currently know how to vectorize it. However, one could change the CRC implementation to hardware intrinsics if these are given.

See [https://www.felixcloutier.com/x86/crc32](https://www.felixcloutier.com/x86/crc32).

### Intel Compiler Intrinsics
```h
unsigned int _mm_crc32_u8(unsigned int crc, unsigned char data);
unsigned int _mm_crc32_u16(unsigned int crc, unsigned short data);
unsigned int _mm_crc32_u32(unsigned int crc, unsigned int data);
unsigned __int64 _mm_crc32_u64(unsigned __int64 crc, unsigned __int64 data);
```

**Comment by BenjaminRi** [comment]
Are you sure that these crc32 methods use the same polynomial as the one used in ZipCrypto? I briefly looked into it and it looks like it's the wrong crc32.

https://en.wikipedia.org/wiki/X86_instruction_listings#Added_with_SSE4.2

> Computes CRC value using the CRC-32C (Castagnoli) polynomial 0x11EDC6F41 (normal form 0x1EDC6F41). This is the polynomial used in iSCSI. In contrast to the more popular one used in Ethernet, its parity is even, and it can thus detect any error with an odd number of changed bits. 

https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.3.TXT

>    Where update_keys() is defined as:
>
>    update_keys(char):
>      Key(0) <- crc32(key(0),char)
>      Key(1) <- Key(1) + (Key(0) & 000000ffH)
>      Key(1) <- Key(1) * 134775813 + 1
>      Key(2) <- crc32(key(2),key(1) >> 24)
>    end update_keys
>
>    Where crc32(old_crc,char) is a routine that given a CRC value and a
>    character, returns an updated CRC value after applying the CRC-32
>    algorithm described elsewhere in this document.

If we look "elsewhere in this document" (what an odd reference, imagine if this document described two different CRC-32):

> 4.4.7 CRC-32: (4 bytes)
>
>    The CRC-32 algorithm was generously contributed by
>    David Schwaderer and can be found in his excellent
>    book "C Programmers Guide to NetBIOS" published by
>    Howard W. Sams & Co. Inc.  The 'magic number' for
>    the CRC is 0xdebb20e3.

If you look at the Wikipedia article, you see that CRC-32C (Castagnoli) is different from the traditional CRC-32 that Ethernet and PKZIP use.

https://en.wikipedia.org/wiki/Cyclic_redundancy_check#Polynomial_representations_of_cyclic_redundancy_checks

I'm open for ZipCrypto optimizations, but if we want to do something about it, we need an actual idea that brings a significant performance benefit. If you submit a pull request or a well documented idea, I'll be the first person to support you with that.

Do you have any performance issues? The current performance seems acceptable (I use this library daily) and should be similar to that of 7zip.

**Comment by Plecra** [comment]
As BenjaminRi has said, a good SIMD would be fantastic ^^ I'd like to see a benchmark with any PR - put it in-tree if possible!
