### ISSUE TITLE
Streaming ZIP

### ISSUE THREAD

**Issue by adhesivee** [zip-rs/zip#256]
For my application I try to stream all the zip contents, instead of writing it to a file first.
I have not found a capability to do so. Also I don't want to keep the whole zip file in memory first before writing.
Essientally I try to achieve something like:

```rust
let mut buf = vec![];
let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));

zip.start_file("file-1.txt", Default::default())?;
zip.write(b"Contents of file 1")?;

// Read contents and reset cursor

zip.start_file("file-2.txt", Default::default())?;
zip.write(b"Contents of file 2")?;

// Read contents and reset cursor

zip.finish()?;

// Read contents and reset cursor
```

I can imagine that this can cause issues because `ZipWriter` requires `Seek`, but I wonder if that is needed for all cases.

**Comment by Plecra** [comment]
We are tracking this feature in #16! We agree it'll be a great addition.
