### ISSUE TITLE
Update time dependency to >= 0.2.23

### ISSUE THREAD

**Issue by kirillbobyrev** [zip-rs/zip#257]
The Rust Advisory Database [indicates](https://rustsec.org/advisories/RUSTSEC-2020-0071.html) there is a potential security vulnerability in the `time` crate. This shows up in the security audit for my crate.

I don't know if I'm doing something wrong or if it's expected, but since `time` dependency is optional, I remove the `time` feature from `zip` but I still end up with `time` in my `Cargo.lock`, which means the security audit checks will continue complaining for me even though I don't use `time` at all.

**Comment by kirillbobyrev** [comment]
Oh, okay, I tried to disable it in a wrong way:

```toml
[dependencies.zip]
version = "0.5"
default_features = false
```

works. But it still makes a lot of sense to update `time`.

**Comment by zamazan4ik** [comment]
Resolved with https://github.com/zip-rs/zip/pull/254

**Comment by kirillbobyrev** [comment]
Thanks a lot!

**Comment by zamazan4ik** [comment]
I think we will be able to release the new version in some time (since I need to check all open PRs, update dependencies, and so on). At least for now, you can use the version from the `master` branch.
