### ISSUE TITLE
Accidental API break in ZSTD PR

### ISSUE THREAD

**Issue by Plecra** [zip-rs/zip#266]
https://github.com/zip-rs/zip/blob/afc84af4aafa2af8c4b1d10693d366b6c640002f/src/compression.rs#L27-L29

This enum isn't `non_exhaustive` so this change is breaking. We need to remove it and update the code to use the existing `CompressionMethod::ZSTD` (and `CompressionMethod::ZSTD_DEPRECATED`)

**Comment by zamazan4ik** [comment]
I think it can be closed now
