### ISSUE TITLE
compress 614MB directory with Deflated method ,it takes about 5 minutes......

### ISSUE THREAD

**Issue by bmiyuan** [zip-rs/zip#279]
If use Stored method to compress a directory ,it takes about 8 seconds to compress 614MB directory, but it takes about 5 minutes when I use Deflated or Bzip2 methods.... is this a known issue?  very appreciated if somebody can give some advices on this issue.

**Comment by zamazan4ik** [comment]
@bmiyuan could you please prepare the minimal reproducible example, please? I think some GitHub repo with the code and testing directory somewhere with the data will allow us to investigate the issue deeper.

Also, could you please share with us information about your env? OS version, Rust version, maybe filesystem type or any other important from your point of view information.

Thanks!

**Comment by bmiyuan** [comment]
@zamazan4ik thanks your quick response.

I test again with below code to compress a file of 264MB, and it takes  116.8018525s.
Test Result:Time elapsed in expensive_function() is: 116.8018525s
rustc vesrion is 1.58.1 and cargo version is cargo 1.58.0 
OS: windows 10 professional edition

`fn compress_dir(zipfilename: &str) -> zip::result::ZipResult<()> {
    let path = std::path::Path::new(zipfilename);
    let file = std::fs::File::create(&path).unwrap();
    let mut zip = zip::ZipWriter::new(file);
    let options = FileOptions::default().compression_method(zip::CompressionMethod::Deflated);
    let srcfile = "x";//you can repace x with any ansolute path of large file or directory here
    let f = File::open(srcfile);
    zip.start_file(srcfile, options)?; 
    let mut srcfile = f.unwrap();
    copy(&mut srcfile, &mut zip).unwrap();
    zip.finish()?;
    Ok(())
}`

**Comment by zamazan4ik** [comment]
Thanks! Could you provide please a little bit more information:

1. Which `zip-rs` version do you use?
2. What kind of files do you have in this folder? A lot of small files or some amount of quite big files? Are there nested directories?

@Plecra do you know anything about existing similar issues? My first guess would be I guess that we have some quite aggressive optimization levels for Deflate and BZip2 methods. Also, maybe we already know about some inefficiencies in our implementations.

**Comment by bmiyuan** [comment]
@zamazan4ik  
Hi, some more information here:
1. zip = "0.5" ,the github  link  is [https://github.com/zip-rs/zip](url) 
2. I've tested a directory of 614MB  which has many files and subdirectories , besides I also tested a zip file which is 264MB, I think you can reproduce this issue with other big file or directory.

**Comment by bmiyuan** [comment]
@zamazan4ik it seems it's an issue....can we change the tag to bug or need an enhancement?

**Comment by zamazan4ik** [comment]
@bmiyuan Yes, I think we should mark it as an enhancement at least

**Comment by bmiyuan** [comment]
@zamazan4ik do you know whether is there anyone work on this enhancement?

**Comment by zamazan4ik** [comment]
I have not enough time to work on it, sorry :(

**Comment by bmiyuan** [comment]
OK,thanks :smiley:

**Comment by Plecra** [comment]
I'm afraid I can't do much with this. It sounds possible that your performance is degrading because you're opening and reading so many files - Windows in particular can be pretty bad at that. But really, I can only make performance improvements to specific routines that people are having problems with.
