### ISSUE TITLE
Broken ZIP files created by commit a1da686

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [zip-rs/zip#291]
PR #290 (rev a1da6860ea423e999b731fca866ed54505e0096e) appears to have broken writing, at least header writing. Creating test.zip by my example code in #287, tools report:

7-Zip: 

```
Error: Headers Error
Unconfirmed start of archive

Warning: Headers Error
There are some data after the end of the payload data
```

`zip -T test.zip` (zip 3.0-11build1 on Ubuntu 20.04):

```
  error:  invalid compressed data to inflate testfile
test of test.zip FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
```

Neither 7-Zip nor `unzip` can extract the archive created by this library.

The same code, when using rev 574bb3df1748a89c8cb1dbed65e625526e4496ee, the immediately preceding commit, creates a working ZIP file.

**Comment by zamazan4ik** [comment]
@aweinstock314 check the issue please

**Comment by zamazan4ik** [comment]
@AlyoshaVasilieva I am sorry for the broken master branch. At least it shows that now we have lack of tests

**Comment by zamazan4ik** [comment]
If we do not fix the issue quickly - I will revert the corresponding PR.

**Comment by AlyoshaVasilieva** [comment]
No worries about broken master, better now than released.

I'm not good at writing CI but I'd recommend maybe creating test files and using `zip -T` command on a Linux runner to test them as a possible improvement to testing. It won't find everything (e.g. I think it doesn't care about wrong local headers if central record is fine) but it would detect broken files like here.

**Comment by n3vu0r** [comment]
I'm on it.

**Comment by zamazan4ik** [comment]
I have reverted the changes in master branch. So if you want to continue the work - please rebase :)

**Comment by n3vu0r** [comment]
Does the fix as part of #292 pass your tests?

**Comment by zamazan4ik** [comment]
@AlyoshaVasilieva could you confirm please that with the latest release the issue is resolved? Thanks!

**Comment by AlyoshaVasilieva** [comment]
I believe it was fixed, will test again once I wake up

**Comment by AlyoshaVasilieva** [comment]
The test I've been using works fine with 0.6.2. Also works fine with the rejected PR #292.
