### ISSUE TITLE
mips cross-compile fail with 0.6.x but works on 0.5x

### ISSUE THREAD

**Issue by axetroy** [zip-rs/zip#299]
When I cross-compile to mips

![截屏2022-04-05 17 32 10](https://user-images.githubusercontent.com/9758711/161724592-f8e344d3-22b4-441d-aae2-9921785f8226.png)

https://github.com/cask-pkg/cask.rs/runs/5830751498?check_suite_focus=true

Before I upgrade to 0.6.x, it can compile success

**Comment by n3vu0r** [comment]
Your build tries to compile zip version `0.6.0` in line [442](https://github.com/cask-pkg/cask.rs/runs/5830751498?check_suite_focus=true#step:4:442). It should be fixed for mips with `0.6.1` and for arm32 with `0.6.2`.

**Comment by axetroy** [comment]
> Your build tries to compile zip version `0.6.0` in line [442](https://github.com/cask-pkg/cask.rs/runs/5830751498?check_suite_focus=true#step:4:442). It should be fixed for mips with `0.6.1` and for arm32 with `0.6.2`.

Yeah, it has been fixed in 0.6.1. confirm. and thanks
