### ISSUE TITLE
Support unzip without override?

### ISSUE THREAD

**Issue by bigdogs** [zip-rs/zip#301]
Hi, 

Does this library support unzip a file without override/replace exist file?  

For `unzip` command on MacOS,  it will prompt to user to take a choice.  But for  this crate, I didn't find any options to make the choice, and the behavior seems is override/replace, which is not what I want

```
/tmp % unzip -d 1 1.apk
...
  inflating: 1/res/-r.xml            
  inflating: 1/res/-r1.xml           
  inflating: 1/res/-s.xml            
replace 1/res/-u.png? [y]es, [n]o, [A]ll, [N]one, [r]ename:  

```

**Comment by Plecra** [comment]
Yeah the `extract` API is half-baked I'm afraid :). To extract zip files with your own logic, you should enumerate the files within the archive and write them to disk yourself.
