### ISSUE TITLE
Lazily decompress files?

### ISSUE THREAD

**Issue by Storyyeller** [zip-rs/zip#312]
Is there any good way to iterate over all the files in a zip and decompress the files with a given extension without paying the cost of decompressing other files?

Write now, it appears that the only way to access the filename of a file is to call by_index() or by_index_raw() and the former decompresses eagerly while the later doesn't decompress at all and there is no way to get access to the uncompressed data.

**Comment by zamazan4ik** [comment]
@Plecra any suggestion?)

**Comment by Plecra** [comment]
That's the current behaviour of the crate :) you may iterate files, check their names `by_index`, and only read them if they match your filter. They won't be decompressed if you do not read them.

I'll close for now. If I've misunderstood you, go ahead and reopen ^^
