### ISSUE TITLE
Decompress from stream

### ISSUE THREAD

**Issue by NobodyXu** [zip-rs/zip#314]
Here in [`cargo-binstall`](https://github.com/ryankurte/cargo-binstall), we are forced to write the downloaded file first to the disk, then pass it to `ZipArchiver` whereas all the other algorithms we support (gzip, xzip and zstd) have a streaming interface that just accepts `BufRead` (and `Read` for convenience).

Is it possible for zip to have a streaming interface that takes `BufRead`?

**Comment by zamazan4ik** [comment]
Yes, you can. But this library is in maintenance-only state. So if you want to implement it, the best idea is prepare a PR and send it here :) I will try to review and merge it.

**Comment by NobodyXu** [comment]
I have zero knowledge on zip's codebase, but I will spend my time to understand and hopefully it won't be too complicated to add this feature.

**Comment by zamazan4ik** [comment]
@NobodyXu unfortunately, I am not the good person for asking questions about ZIP details :) @Plecra I guess you know much more details
