### ISSUE TITLE
Strangly when add file which has same path

### ISSUE THREAD

**Issue by rise0chen** [zip-rs/zip#324]
![image](https://user-images.githubusercontent.com/12853908/196386851-c837d554-62ba-4b14-95bd-6307c5653cb3.png)

![image](https://user-images.githubusercontent.com/12853908/196386982-d0c1d31d-1885-43ab-83d2-adc59d08ccaf.png)

**Comment by Plecra** [comment]
Yup, this is the typical behaviour of zip archives - names don't uniquely identify a file within them. If you want to ensure you dont have duplicates, you might use a `HashSet` to check names before they're entered into the archive
