### ISSUE TITLE
Read only a file in the zip file without decompressing it

### ISSUE THREAD

**Issue by cn-hew** [zip-rs/zip#328]
hi~,
How do I get the file name without a path in a zip? Is there a way to do this? Can I directly read the matching file in the subdirectory based on the file name without caring which directory it is in?

**Comment by Plecra** [comment]
You can inspect the files that you find in an archive with [`ZipArchive::file_names`](https://docs.rs/zip/latest/zip/read/struct.ZipArchive.html#method.file_names). You can implement any searching algorithm you like through that.

Here, it looks like you might use ```rs
let file_name = ...;
for entry in archive.file_names() {
    if entry.ends_with(file_name) {
        // handle the archive.by_name(entry)
    }
}```

**Comment by cn-hew** [comment]
> You can inspect the files that you find in an archive with [`ZipArchive::file_names`](https://docs.rs/zip/latest/zip/read/struct.ZipArchive.html#method.file_names). You can implement any searching algorithm you like through that.
> 
> Here, it looks like you might use `rs let file_name = ...; for entry in archive.file_names() { if entry.ends_with(file_name) { // handle the archive.by_name(entry) } }`

thanks bro  i used your method it really works I'm not familiar with rust

**Comment by cn-hew** [comment]
Hi,bro~
I'm bothering you again. How can I read the file content without extracting it
I have come to trouble you again. How can I read the file content without extracting it now? The last two lines will have path errors, and should not be transmitted in this way?
```
let path = std::path::Path::new("C:\\hewei\\code\\clara_analysis\\clara_xml_analysis\\Report_Summary_2022-10-17-20-36-53.zip");
    let open_file = fs::File::open(&path).unwrap();

    let archive = zip::ZipArchive::new(open_file).unwrap();

    let clara_name = String::from("_summary.clara");
    let mut buf = String::new();
    for i in archive.file_names() {
        
        if i.ends_with(&clara_name) {
               println!("{}",i)
        //     let mut clara_summary_content = File::open(i).expect("read file failed");
        //     clara_summary_content.read_to_string(&mut buf);
               
        
            
        }
        
    }
```
