### ISSUE TITLE
to_owned or OwnedZipFile method?

### ISSUE THREAD

**Issue by cottrell** [zip-rs/zip#329]
I think it could be beneficial to have some to_owned method here and possibly elsewhere? Or is there perhaps a more fundament way of doing this?

https://docs.rs/zip/latest/zip/read/struct.ZipArchive.html#method.by_index

```rust
fn by_index2(self, file_number: usize) -> ZipResult<OwnedZipFile>
```

**Comment by Plecra** [comment]
I'm going to say we're not adding this for now (you're right though, it's a useful api!). If you'd like an owned zip file, use https://docs.rs/ouroboros to build a self referencing `(ZipArchive, ZipFile<'_>)`.
