### ISSUE TITLE
Files inside extracted zips don't have the correct `last_modified` timestamps

### ISSUE THREAD

**Issue by neil-morrison44** [zip-rs/zip#331]
Hi there,

I'm using this crate in something that uses zips as a backup medium, where I'm looking to compare timestamps of files between zips etc.

So I can use this crate to _save_ the timestamp into the zip correctly using `options.last_modified_time` & other apps (e.g. Finder) will extract the files out with the metadata attached -- but when I'm using `archive.extract` all the files are given a `last_modified` timestamp of whenever the extract happened.

Not sure if there's an option on `extract` that I'm missing?

Thanks

**Comment by Plecra** [comment]
There isn't. You'll need to write custom extraction logic - check out the `examples/extract.rs` file. 

(Unfortunately a more widely useful `extract`ion routine is out of scope for the moment)
