### ISSUE TITLE
Updating aes crate.

### ISSUE THREAD

**Issue by plugwash** [zip-rs/zip#352]
We have been looking into upgrading the "aes" crate in debian (it won't happen now until after the bookworm freeze), and one of the reverse dependencies is the zip crate. While we do have a mechanism for packaging multiple versions of crates it is something we try to avoid where possible.

Is there any chance of an update of the zip crate to use the latest version of the aes crate. I tried bumping the dependency but quickly ran into build errors.

**Comment by Plecra** [comment]
Sure, that'd be wise. I'll have a look at whether the transition would be easy.

**Comment by Pr0methean** [comment]
https://crates.io/crates/zip_next version 0.8.2 uses AES 0.8.2.
