### ISSUE TITLE
Add a function to check file name exists, without iterator over all names by file_names()

### ISSUE THREAD

**Issue by zangloo** [zip-rs/zip#438]
I'm writing a program, that need to check a lot of referenced files exists in the zip file without open it. If the zip containt a lot of files,  the check will take a lot of time.
I found the file_names() is collect the names of a map, so maybe add a funciton like 
`pub fn file_exists(name: &str)`
will be much faster then iterate all file names.

**Comment by Pr0methean** [comment]
You can use `by_name(name) != Err(ZipError::FileNotFound)`.

**Comment by zangloo** [comment]
I just want check if the file is exists, if using by_name() and the file exists, it will create a reader, do seek, read header, calc the size, etc... . And i may check a file list existance for every file, then by using by_name, will cause a lot of useless operations.

**Comment by Pr0methean** [comment]
Fixed by https://github.com/Pr0methean/zip/commit/16b66841b30998773ebca46755d10ae1a476bbb8 which will release in version 1.1.1.

**Comment by zangloo** [comment]
That's great. Thanks.
