### ISSUE TITLE
This crate is unmaintained

### ISSUE THREAD

**Issue by Pr0methean** [zip-rs/zip#446]
In accordance with https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md, please create an advisory to indicate that this crate is unmaintained. If this isn't done by 2024-07-16 and I don't see any maintenance activity by then, I will create it myself. Affected users should upgrade to https://crates.io/crates/zip_next.

**Comment by a1phyr** [comment]
Hi @Plecra ! If you need help maintaining this crate, I can give a hand from time to time.

**Comment by Pr0methean** [comment]
Sure, I'd be glad to take over the `zip` name and make `zip-next` a
re-export.

**Comment by Pr0methean** [comment]
@Plecra Have you added me as an owner to `zip`? If so, I'll publish `zip-next` under the name `zip` within 24 hours, then make `zip-next` a wrapper within 24 hours of that.

**Comment by Plecra** [comment]
That should be done now :)

**Comment by Pr0methean** [comment]
Published as `zip`, made `zip_next` a wrapper, and opened https://github.com/rustsec/advisory-db/pull/1949 to advise of the name change.

**Comment by Pr0methean** [comment]
@Plecra May I please be an admin on this repo, so I can close issues and PRs that are addressed in mine?

**Comment by djc** [comment]
I definitely got confused by having two seemingly active repos -- would be nice to get this archived. Maybe it makes sense to move `Pr0methean/zip` into `zip-rs` and rename this as `zip-rs/zip-old`?

**Comment by Plecra** [comment]
I'll leave that up to @Pr0methean

**Comment by Pr0methean** [comment]
Renaming the new repo to zip-rs/zip would cause old issue and PR links to point to the wrong item. But I'll rename this repo to zip-old once @Plecra makes me an admin.

I also agree that this repo should be archived eventually, but I'd like to at least triage the open issues and PRs first, copy over the ones that are still valid, and close them. If the repo is archived with open issues and PRs, they'll become stuck open.

**Comment by RouHim** [comment]
Smells like xz, just kidding ;)

**Comment by djc** [comment]
> Smells like xz, just kidding ;)

You joke, but IMO this is a scenario where it might make sense to ask @Pr0methean (with no ill intent) to declare/demonstrate somehow why they're trustworthy to take over this pretty popular crate name, and/or to explore other options. This moved pretty quickly.

**Comment by Pr0methean** [comment]
@djc I think my work on the fuzz tests speaks for itself.

And I have an incentive to keep going: I'm likely to be looking for a new job soon, so I need an open-source project in my portfolio that people have actually heard of and submitted issues and PRs against. From that perspective, `zip` was the right crate at the right time.

**Comment by Pr0methean** [comment]
Also keep in mind that I'll be glad to work with another maintainer if and when one shows up.

**Comment by Pr0methean** [comment]
@Plecra Today I found out about GitHub's merge-queue feature (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue). It seems like it would make it much easier to contribute a pull request when there are already PRs open. But it requires the repository to belong to an organization. What would you say to the idea of my becoming an org admin and transfering my repo to `zip-rs/zip2`, while this one becomes `zip-rs/zip1`?

**Comment by jayvdb** [comment]
According to https://github.com/zip-rs/zip/graphs/contributors , @Pr0methean has had zero contributions to *this* original project.  Is that right?

One of the major reasons for the "xz" hack was the new owner was actually anonymous, using the name Jia Tan (@JiaT75).  I've done a bit of googling, and @Pr0methean has a more normal digital footprint than @JiaT75 did.
Still, two hours ago I sent an email to the unverified email address in [this commit](https://github.com/Pr0methean/zip/commit/1663321323813eb1c6aa51aa1f2329961d2c15f4) to check that the identities line up.  No response yet.  Apologies Chris, but we need to check who is taking over projects/orgs that have a lot of dependencies, and very high number of downloads per day.

**Comment by Pr0methean** [comment]
I responded from that email address once I saw your latest comment; I wasn't watching it because it's a work email and I'm on leave.

**Comment by RouHim** [comment]
> > Smells like xz, just kidding ;)
> 
> You joke, but IMO this is a scenario where it might make sense to ask @Pr0methean (with no ill intent) to declare/demonstrate somehow why they're trustworthy to take over this pretty popular crate name, and/or to explore other options. This moved pretty quickly.

In fact, it was a joking comment intended to make people aware of the situation. 

I'm going to freeze my zip dependencies until this situation is clear.

**Comment by jayvdb** [comment]
Response received. And with that I can verify Chris' linkedin.

**Comment by joaommartins** [comment]
> Response received. And with that I can verify Chris' linkedin.

And how do we know you're not working with _them_? 🤔

**Comment by RouHim** [comment]
Ok, if that's the case, it was a really badly requested and executed change of ownership in view of the current situation.

**Comment by liningpan** [comment]
It would be really help to document this change and mark this repo as unmaintained / point to the new repo. It's kind of scary to see crates.io suddenly points to a different location.

**Comment by x87** [comment]
I was considering using this crate in some of my projects, but in the view of recent events this sudden ownership transfer gives me zero confidence. Especially since zip is also a highly dependent on archive library. I'll pass 👋

**Comment by RouHim** [comment]
I really hope this ends well:
![image](https://github.com/zip-rs/zip/assets/3582050/700d25a6-9d4d-418d-8c5f-1a6a71abfd7d)

**Comment by Pr0methean** [comment]
@a1phyr In case you'd still like to help, I've moved as many as possible of this repo's open PRs into https://github.com/zip-rs/zip2/pulls; and as a member, you should be able to help fix the ones that didn't successfully build after merging (marked with X).

**Comment by Pr0methean** [comment]
@cosmicexplorer Same for you.

**Comment by Pr0methean** [comment]
@x87 What can I do to restore your confidence in https://github.com/zip-rs/zip2?

**Comment by CommanderStorm** [comment]
> What can I do to restore your confidence in https://github.com/zip-rs/zip2?

Honestly, nothing.
Trust in maintainers is currently at an all-time low (for good reason). I think that will recover.
I see trust as a function over time, people will do semi-regular audits of the crate going forward. Nothing you need to worry or can do anything about ^^

But given that there are a lot of very cool performance improvements you are working on maybe consider doing a talk at one of the many Rust conferences. "Knowing" somebody is a real human should help with the trust problem.

I would put my money where my mouth is and sponsor you (the work you have put into this library definitively warrants that), but GitHub sponsors does only allow Credit cards
=> would you consider opening an open collective account for https://github.com/zip-rs or https://github.com/Pr0methean? 😉

**Comment by Pr0methean** [comment]
> I would put my money where my mouth is and sponsor you (the work you have put into this library definitively warrants that), but GitHub sponsors does only allow Credit cards
> => would you consider opening an open collective account for https://github.com/zip-rs or https://github.com/Pr0methean?

Done; I've created https://opencollective.com/rust-compressed-archive-collec to represent us at Open Collective, and I've applied to have Open Collective Europe ASBL serve as the fiscal host (since they've been the only fiscal host with 501c3-equivalent tax treatment in the US since the Open Collective Foundation dissolved).

@a1phyr @Plecra I've invited you to be my co-administrators; will you accept?

**Comment by Pr0methean** [comment]
@cosmicexplorer Are you on opencollective.com? If so, I've invited you as well; if not, I'd like to invite you but will need an email address to reach you at. (You can commit it to https://github.com/zip-rs/PrivateInfo to make it visible to zip-rs members only.)
