### ISSUE TITLE
Parallel decompression of a single entry

### ISSUE THREAD

**Issue by sanmai-NL** [zip-rs/zip#46]
It seems the requirement in #14 is a bit different from mine. I am currently stress testing `zip-rs` and I found that it uses 100 % of a single logical CPU for quite a long time on a beefy workstation just to decompress a 4 GiB large file consisting of zeroes. Would it be possible to distribute decompression across logical CPUs? I couldn't quickly make Rayon's [parallel iterators](https://github.com/rayon-rs/rayon/tree/f1c27825119987c018e10ccfb7c5ccd59d781d8b#parallel-iterators) work.

**Comment by Plecra** [comment]
This would be very cool to be able to do. Our dependencies can't handle parallelization though, and I don't expect to be able to soon (we have problems with IO being sequential: deflate decompression will often keep up with even modern drives).
